package net.javahippie.fitpub.model.entity;

import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Entity representing a remote fitness activity from another FitPub instance or ActivityPub server.
 *
 * IMPORTANT: This entity stores METADATA ONLY - no full track data.
 * Track visualization is done via remote map image URLs pointing to the origin server.
 */
@Entity
@Table(name = "remote_activities", indexes = {
    @Index(name = "idx_remote_activity_uri", columnList = "activity_uri", unique = true),
    @Index(name = "idx_remote_activity_actor", columnList = "remote_actor_uri"),
    @Index(name = "idx_remote_activity_published", columnList = "published_at"),
    @Index(name = "idx_remote_activity_visibility", columnList = "visibility")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RemoteActivity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    /**
     * ActivityPub activity URI (globally unique identifier).
     * Example: https://fitpub.example/activities/12345
     */
    @Column(name = "activity_uri", nullable = false, unique = true, length = 512)
    private String activityUri;

    /**
     * ActivityPub actor URI of the user who created this activity.
     * Example: https://fitpub.example/users/alice
     */
    @Column(name = "remote_actor_uri", nullable = false, length = 512)
    private String remoteActorUri;

    /**
     * Type of activity (RUN, RIDE, HIKE, SWIM, etc.).
     */
    @Column(name = "activity_type", length = 50)
    private String activityType;

    /**
     * Activity title.
     */
    @Column(name = "title", nullable = false, length = 500)
    private String title;

    /**
     * Activity description/notes.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * When the activity was published (from ActivityPub).
     */
    @Column(name = "published_at", nullable = false)
    private Instant publishedAt;

    /**
     * Total distance in meters.
     */
    @Column(name = "total_distance")
    private Long totalDistance;

    /**
     * Total duration in seconds.
     */
    @Column(name = "total_duration_seconds")
    private Long totalDurationSeconds;

    /**
     * Total elevation gain in meters.
     */
    @Column(name = "elevation_gain")
    private Integer elevationGain;

    /**
     * Average pace in seconds per kilometer (for runs).
     */
    @Column(name = "average_pace_seconds")
    private Long averagePaceSeconds;

    /**
     * Average heart rate in BPM.
     */
    @Column(name = "average_heart_rate")
    private Integer averageHeartRate;

    /**
     * Maximum speed in km/h.
     */
    @Column(name = "max_speed")
    private Double maxSpeed;

    /**
     * Average speed in km/h.
     */
    @Column(name = "average_speed")
    private Double averageSpeed;

    /**
     * Calories burned (if provided).
     */
    @Column(name = "calories")
    private Integer calories;

    /**
     * URL to the map image on the remote server.
     * This points to a static map image generated by the origin server.
     */
    @Column(name = "map_image_url", length = 512)
    private String mapImageUrl;

    /**
     * URL to the GeoJSON track data on the remote server (optional).
     * If provided, allows dynamic map rendering.
     */
    @Column(name = "track_geojson_url", length = 512)
    private String trackGeojsonUrl;

    /**
     * Visibility level of the activity.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "visibility", nullable = false, length = 20)
    private Visibility visibility;

    /**
     * Full ActivityPub object as JSON (for future re-parsing or debugging).
     * Stored as JSONB for efficient querying.
     */
    @Type(JsonBinaryType.class)
    @Column(name = "activitypub_object", columnDefinition = "jsonb")
    private String activityPubObject;

    /**
     * Timestamp when this record was created locally.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this record was last updated.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Visibility levels for remote activities.
     */
    public enum Visibility {
        /**
         * Public activity visible to everyone.
         */
        PUBLIC,

        /**
         * Activity visible only to followers.
         */
        FOLLOWERS,

        /**
         * Private activity (should not be federated, but included for completeness).
         */
        PRIVATE
    }
}
