create table gadm_410
(
    fid        serial
        primary key,
    uid        bigint,
    gid_0      varchar(10),
    name_0     varchar(32),
    varname_0  varchar(29),
    gid_1      varchar(10),
    name_1     varchar(34),
    varname_1  varchar(82),
    nl_name_1  varchar(87),
    iso_1      varchar(10),
    hasc_1     varchar(10),
    cc_1       varchar(10),
    type_1     varchar(32),
    engtype_1  varchar(32),
    validfr_1  varchar(15),
    gid_2      varchar(12),
    name_2     varchar(34),
    varname_2  varchar(39),
    nl_name_2  varchar(75),
    hasc_2     varchar(15),
    cc_2       varchar(12),
    type_2     varchar(34),
    engtype_2  varchar(32),
    validfr_2  varchar(15),
    gid_3      varchar(15),
    name_3     varchar(38),
    varname_3  varchar(44),
    nl_name_3  varchar(56),
    hasc_3     varchar(27),
    cc_3       varchar(10),
    type_3     varchar(32),
    engtype_3  varchar(32),
    validfr_3  varchar(10),
    gid_4      varchar(18),
    name_4     varchar(34),
    varname_4  varchar(35),
    cc_4       varchar(12),
    type_4     varchar(29),
    engtype_4  varchar(29),
    validfr_4  varchar(10),
    gid_5      varchar(19),
    name_5     varchar(34),
    cc_5       varchar(10),
    type_5     varchar(22),
    engtype_5  varchar(10),
    governedby varchar(17),
    sovereign  varchar(32),
    disputedby varchar(32),
    region     varchar(32),
    varregion  varchar(48),
    country    varchar(32),
    continent  varchar(13),
    subcont    varchar(10),
    geom       geometry(MultiPolygon, 4326)
);

create index geodata_pkey_geom_geom_idx
    on gadm_410 using gist (geom);

